### GENERAL SETTINGS ###

# Site settings
title: BVPT
description: "BV PT is a physiotherapy and personal training clinic located in North Lakes, Brisbane.  We are highly skilled in treating a wide range of injuries, an achieving peak performance across all stages of function."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/mashical.github.io" #important: start with /
url: "https://mashical.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 4553, North Lakes,
    - Brisbane
    - Australia
email: hello@bvpt.com.au
tel: 0400 000 000


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: B V
    position: Senior Physiotherapist, Personal Trainer
    text: Highly experienced in private practice, sports physiotherapy, community care and aged care.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: Tonga Samoa Rugby League
    img: client01.png
  - name: Richmod Rovers
    img: client02.png
  - name: Eden Rugby Union FC
    img: client03.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "BV PT is a physiotherapy and personal training clinic located in North Lakes, Brisbane.  We are highly skilled in treating a wide range of injuries, an achieving peak performance across all stages of function."  

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Your Health, Our Responsibility"
    author: B V
    position: Physiotherapist
